# Point to Stratum 1 Server
server 172.18.0.1 iburst burst minpoll 3 maxpoll 3 true prefer

# Tinker Tuning
# - dispersion 15: Widens internal filter to prevent high-jitter rejection
tinker step 0.001 panic 0 dispersion 15

# Max Distance
# - maxdist 0.8: Safely accepts up to 800ms total network error ceiling
tos maxdist 0.8

# File tracking
driftfile "C:\Program Files (x86)\NTP\etc\ntp.drift"
