# /etc/chrony/chrony.conf

# 1. gpsd Primary GPS + PPS Sources
refclock SHM 0 poll 0 refid GPS delay 0.100 trust
refclock SHM 1 poll 0 refid PPS lock GPS precision -20 trust

# serial nmea
# refclock NMEA /dev/ttyUSB0:38400 poll 0 refid GPS

local stratum 1

# 2. Local Hardware Clock Fallback (Used only if GPS fails)
refclock local stratum 10 refid LCL

# Allow instant clock correction on server startup
makestep 0.001 -1

allow all
ratelimit interval -10 burst 9999 leak 9999
clientloglimit 10485760

# Enable Hardware Timestamping if your Network Interface Card (NIC) supports it
# hwtimestamp eth0

# Store clock frequency drift
driftfile /var/lib/chrony/drift
