# /etc/chrony/chrony.conf

# Point to Stratum 1 GPS Server
# - iburst: Rapid 8-packet burst on startup/reconnect for instant initial offset calculation
# - minpoll 0 maxpoll 2: Polls every 1 to 4 seconds (ideal for a short 15-min window)
# - maxsamples 32: Swaps to a huge 32-packet sliding filter to mathematically average out the jitter
# - maxdelay 0.8: Safely accepts packets up to 800ms to clear your 650ms spikes
# - xleave: Enables interleaved mode to cut out client-side kernel queuing delay
server 172.18.0.1 iburst minpoll 0 maxpoll 2 maxsamples 32 maxdelay 0.8 xleave prefer

# Allow the clock to step instantly at ANY time if off by > 1ms (0.001s)
makestep 0.001 -1

# Directory to dump measurement history when shutting down/disconnecting
dumpdir /var/lib/chrony

# Location for saving clock frequency drift between boots
driftfile /var/lib/chrony/drift
dumpdir /var/lib/chrony